'use client';

import { annotation as csAnnotation } from '@cornerstonejs/tools';

export const MEASUREMENT_COLOR = 'rgb(0, 255, 0)';
export const SELECTED_MEASUREMENT_COLOR = 'rgb(255, 255, 0)';

type AnnotationStyle = Record<string, unknown>;

const managedAnnotationUIDs = new Set<string>();
const originalStyles = new Map<string, AnnotationStyle | undefined>();
const appliedSelectionState = new Map<string, boolean>();
let selectedAnnotationUID: string | null = null;

function getAnnotationStyles(isSelected: boolean): AnnotationStyle {
  const displayColor = isSelected
    ? SELECTED_MEASUREMENT_COLOR
    : MEASUREMENT_COLOR;

  return {
    color: displayColor,
    colorHighlighted: displayColor,
    colorSelected: displayColor,
    colorLocked: displayColor,
    colorAutoGenerated: displayColor,
    textBoxColor: displayColor,
    textBoxColorHighlighted: displayColor,
    textBoxColorSelected: displayColor,
    textBoxColorLocked: displayColor,
    textBoxColorAutoGenerated: displayColor,
  };
}

function setAnnotationStyles(annotationUID: string, isSelected: boolean): void {
  if (!annotationUID || appliedSelectionState.get(annotationUID) === isSelected) {
    return;
  }

  try {
    const style = csAnnotation.config?.style;
    if (!style?.setAnnotationStyles) return;

    if (!originalStyles.has(annotationUID)) {
      const existingStyles = style.getAnnotationToolStyles?.(annotationUID);
      originalStyles.set(
        annotationUID,
        existingStyles ? { ...existingStyles } : undefined
      );
    }

    style.setAnnotationStyles(annotationUID, {
      ...(originalStyles.get(annotationUID) ?? {}),
      ...getAnnotationStyles(isSelected),
    });
    managedAnnotationUIDs.add(annotationUID);
    appliedSelectionState.set(annotationUID, isSelected);
  } catch {
    // Rendering styles are best-effort; a missing style API must not break the viewer.
  }
}

function syncCornerstoneSelection(annotationUID: string | null): void {
  try {
    const selection = csAnnotation.selection as any;
    const selectedUIDs: string[] =
      selection?.getAnnotationsSelected?.() ?? [];

    if (!annotationUID) {
      if (selectedUIDs.length > 0) {
        selection?.deselectAnnotation?.();
      }
      return;
    }

    if (
      selectedUIDs.length !== 1 ||
      selectedUIDs[0] !== annotationUID
    ) {
      selection?.setAnnotationSelected?.(annotationUID, true, false);
    }
  } catch {
    // Native selection is an interaction aid; visual selection still works
    // through the annotation-specific styles above.
  }
}

export function releaseMeasurementAnnotationStyle(annotationUID: string): void {
  if (!annotationUID || !managedAnnotationUIDs.has(annotationUID)) return;

  try {
    const style = csAnnotation.config?.style;
    const original = originalStyles.get(annotationUID);

    if (original) {
      style?.setAnnotationStyles?.(annotationUID, original);
    } else {
      // Cornerstone has no public remove API for annotation styles. Reset via
      // the public setter first, then remove the now-empty entry when exposed.
      style?.setAnnotationStyles?.(annotationUID, {});
      const configuredAnnotations = (style as any)?.config?.annotations;
      if (configuredAnnotations) {
        delete configuredAnnotations[annotationUID];
      }
    }
  } catch {
    // Best-effort cleanup only.
  } finally {
    managedAnnotationUIDs.delete(annotationUID);
    originalStyles.delete(annotationUID);
    appliedSelectionState.delete(annotationUID);
    if (selectedAnnotationUID === annotationUID) {
      selectedAnnotationUID = null;
    }
  }
}

export function configureMeasurementToolGroupStyles(toolGroupId: string): void {
  try {
    const style = csAnnotation.config?.style;
    const existingStyles = style?.getToolGroupToolStyles?.(toolGroupId) ?? {};
    const existingGlobalStyles = existingStyles.global ?? {};

    style?.setToolGroupToolStyles?.(toolGroupId, {
      ...existingStyles,
      global: {
        ...existingGlobalStyles,
        ...getAnnotationStyles(false),
      },
    });
  } catch {
    // Best-effort configuration only.
  }
}

export function selectMeasurementAnnotation(annotationUID: string): void {
  if (!annotationUID) return;

  if (
    selectedAnnotationUID &&
    selectedAnnotationUID !== annotationUID &&
    managedAnnotationUIDs.has(selectedAnnotationUID)
  ) {
    setAnnotationStyles(selectedAnnotationUID, false);
  }

  setAnnotationStyles(annotationUID, true);
  selectedAnnotationUID = annotationUID;
  syncCornerstoneSelection(annotationUID);
}

export function syncMeasurementSelectionStyles(
  annotationUIDs: string[],
  selectedMeasurementUID: string | null
): void {
  const uniqueUIDs = Array.from(
    new Set(annotationUIDs.filter((uid) => typeof uid === 'string' && uid.length > 0))
  );
  const measurementUIDs = new Set(uniqueUIDs);
  const selectedUID =
    selectedMeasurementUID && measurementUIDs.has(selectedMeasurementUID)
      ? selectedMeasurementUID
      : null;

  for (const annotationUID of Array.from(managedAnnotationUIDs)) {
    if (!measurementUIDs.has(annotationUID)) {
      releaseMeasurementAnnotationStyle(annotationUID);
    }
  }

  for (const annotationUID of uniqueUIDs) {
    setAnnotationStyles(annotationUID, annotationUID === selectedUID);
  }

  selectedAnnotationUID = selectedUID;
  syncCornerstoneSelection(selectedUID);
}
